### ISSUE TITLE
Extasys server wont accept new connections after specific amount of connections.

### ISSUE THREAD

**Issue by corstian** [nsiatras/extasys#1]
**_This issue is related to the Extasys .NET server. I haven't tested the Java server.**_

When there is a specific amount of clients connected to a single listener the listener stops accepting new connections even when the `MaxConnections` is set to accept (many) more connections. Any existing connections are maintained and handled correctly.

The specific amount of connections varies from machine to machine. (On my local machine it's exactly 1000 connections. On the server where I've tested this the server stops at exactly 195 connections.)

The problem is in the `DoListen` method in the `Extasys\Network\TCP\Server\Listener\TCPListenerThread.cs` file where it keeps hanging on the `fClientConnectionCompleted.WaitOne();` call.

Any thoughts on how to solve this issue?

**Comment by nsiatras** [comment]
Hello Corstian,

I have stopped the\* Extasys .NET\* development a long time ago.
In fact I never tested it with heavy traffic and more than 100 connections.

If you have downloaded the Extasys .NET code please add the following line

_fClientConnectionCompleted.Set();_
after the TCPClientConnection client = new
TCPClientConnection(listener.EndAcceptSocket(ar), fMyListener,
fMyListener.IsMessageCollectorInUse, fMyListener.MessageSplitter); inside
the\* TCPListenerThread.cs*

I think that this is the issue that causes the problem
I am really sorry but at the moment I don't have time for debug and give
you more help.

Nikos

**Comment by corstian** [comment]
It fixed it and as far as I've tested it runs great now! Thanks for the support! (I've created a pull request with this fix applied and tried to clean up some of the Visual Studio related files)

Cheers!

**Comment by nsiatras** [comment]
Thank you for letting me know.

Wish I had the time to finally finish the .NET development :)
