### ISSUE TITLE
Timeout on TCP Client

### ISSUE THREAD

**Issue by fohnbit** [nsiatras/extasys#3]
Hello!

Is it possible to set a timeout for the TCP Client?
When the connection broke, the TCP Cllient did not recognize it .. when I send a new message ... it takes a little bit long with the default timeout.

Thank you!

**Comment by nsiatras** [comment]
In case the client sends a message to the server and the connection is broken the **ExtasysTCPClient.OnDisconnect** method will be fired immediately so you can identify the broken connection.

In my Client/Server applications I prefer to have a Ping thread on the Server to keep up sending a Ping command once in a while. If a client is disconnected and the Server tries to "Ping" him then the **ExtasysTCPServer.OnClientDisconnect** method will be fired immediately.

Let me know how you go with that :)
