### ISSUE TITLE
OnDisconnect fired very often

### ISSUE THREAD

**Issue by fohnbit** [nsiatras/extasys#7]
Hello!

I read ModBus TCP with your library. Unfortunately I get very often a OnDisconnect.

With other TCP clients I never see a problem whiel the TCP connection is open.

Could you imaging where the problem could be? I initiate the TCP with this:
`tcpClient = new TCPClient("Huawei Inverter", "TCP Connection to Huawei inverter", InetAddress.getByName(getPropertyIp()), getPropertyPort(), 5, 10);
tcpClient.Connect();`

My code should only connect 1 TCP Connection to a Huawei inverter and send/read data,

I reconnect after disconnecting. But why did it disconnecting?
Did you have a debug log in your code?

**Comment by nsiatras** [comment]
I think you might need to check for connection time-out interval on the Huawei  side.

Do you send any data to the inverter or you just only read ?

**Comment by nsiatras** [comment]
@fohnbit  PS. Can you upload your TCPClient class in order to check it ?

**Comment by fohnbit** [comment]
Hi!

I'm continuously polling. When I get the response, I start a new request.
After some time the methode OnDisconnect are fired.

I use the TCPClient as innner Class:

```
public TCPClient(String name, String description, InetAddress remoteHostIP, int remoteHostPort,
				int corePoolSize, int maximumPoolSize) {

			super(name, description, corePoolSize, maximumPoolSize);
			super.AddConnector("Main Connector", remoteHostIP, remoteHostPort, 8192);
		}

		public void Connect() {
			try {
				logger.debug("Start Connection");
				forceStopping = false;
				removeAllTickers();
				updateOutputState(ENUM_STATE_STARTING);
				super.Start();
				try {
					tcpClient.getConnectors().get(0).fConnection.setSoTimeout(10000);
				} catch (SocketException e) {
					e.printStackTrace();
				}
				tickOneTime(1000, TICK_POLL, true);
			} catch (Exception ex) {
				logger.error(ex.getLocalizedMessage());
				failedConnection();
			}
		}

		public void Disconnect() {
			try {
				logger.debug("Stop Connection");
				forceStopping = true;
				removeAllTickers();
				updateOutputState(ENUM_STATE_STOPPING);
				super.Stop();
				updateOutputState(ENUM_STATE_STOPPED);

			} catch (Exception ex) {
				logger.error(ex.getLocalizedMessage());
			}
		}

		@Override
		public void OnDataReceive(TCPConnector connector, DataFrame data) {
			parseResponse(data.getBytes());
		}

		@Override
		public void OnConnect(TCPConnector connector) {
			logger.info("Huawei Inverter connected");
			updateOutputState(ENUM_STATE_RUNNING);

		}

		@Override
		public void OnDisconnect(TCPConnector connector) {
			if (!forceStopping) {
				logger.error("onDisconnect fired");
				failedConnection();
			}

		}

	}
```

I start and stop the connection with:
```
@Override
	public void onStart(boolean value) {

		if (value) {
			if (tcpClient != null) {
				tcpClient.Connect();
			} else {
				try {
					tcpClient = new TCPClient("Huawei Inverter", "TCP Connection to Huawei inverter",
							InetAddress.getByName(getPropertyIp()), getPropertyPort(), 5, 10);
					tcpClient.Connect();
				} catch (UnknownHostException e) {
					e.printStackTrace();
				}
			}

		} else {
			if (tcpClient != null)
				tcpClient.Disconnect();
		}
	}

```

I send data to the TCPClient:
```
public void sendData(byte b[]) {
		try {
			tcpClient.SendData(b);
			tickOneTime(TICK_TIMEOUT, 10000, true);
		} catch (ConnectorDisconnectedException | ConnectorCannotSendPacketException e) {
			failedConnection();
			e.printStackTrace();
		}

	}
```

Did you see any problem in my code?

btw: it would be great, when you fied a different methode, when I close "normaly" the connection, or the conenction broke.

**Comment by nsiatras** [comment]
Hello,

I can see that you have implemented a method  named **tickOneTime** and you are calling this method on **sendData** and **Connect** methods.

`tickOneTime(1000, TICK_POLL, true);`

Is the **tickOneTime** method using **thread.sleep()** or pausing the thread in any way?

**Comment by fohnbit** [comment]
Hi!

no, the ticker is a non-blocking thread. I wrote small OSGi applications and the ticker method is from the base system. 

i just use it, when to wait 1s before I send the first data and to check if I get an answer with a given time.

I checked all method and no one trigger when the onDisconnect fired.
Could you add a error description? To see, why the connection disconected.

**Comment by nsiatras** [comment]
So if you need to wait 1second before you send the data, how do you pause the thread?

PS. TCPClient OnDisconnect fires after an error occures on SendData or you call Stop();

**Comment by nsiatras** [comment]
@fohnbit Can you also pass me the parseResponse method ?

**Comment by fohnbit** [comment]
> So if you need to wait 1second before you send the data, how do you pause the thread?
> 
> PS. TCPClient OnDisconnect fires after an error occures on SendData or you call Stop();

I have a method which fired:
```
@Override
	public void tick(int loadId) {
		switch (loadId) {
		case TICK_POLL:
			byte b[] = MyUtils.fromHexString("0x00080000000610037D100048");
			b[6] = (byte) getPropertyModbusid1();
			id = WR1Main;
			b[1] = (byte) id;
			sendData(b);
			timeStamp = Instant.now();
			break;
		case TICK_TIMEOUT:
			logger.debug("Timeout beim abrufen");
			failedConnection();
			break;

		case TICK_RESTART:
			onStart(true);
			break;

		}
	}
```

**Comment by fohnbit** [comment]
> @fohnbit Can you also pass me the parseResponse method ?

this is a very huge method (several hundred lines)

And it is running good ... but after a while it always disconnect. I send always the same data. So I don´t think there is a problem in the rest from the code. 
Because then it should happen at beginning.

**Comment by nsiatras** [comment]
I am a bit confused...

Is the **tickOneTime** method calling **tick** method after a period of time ?

**Comment by nsiatras** [comment]
Ok.. lets do something else here

Please initialize a long variable as the following inside the TCPClient class

```private long fConnectionStartTime;```

Then on OnConnect method add 
```fConnectionStartTime = System.currentTimeMillis();```

and on OnDisconnect method add

```System.out.println("Disconnected after " + String.valueOf(System.currentTimeMillis() - fConnectionStartTime));```

In this way we can can check the disconnect interval

**Comment by fohnbit** [comment]
> I am a bit confused...
> 
> Is the **tickOneTime** method calling **tick** method after a period of time ?

yes, exactly.

Thanks ... but I try in the meantime to extend your code the get an error Message. When the TCP connection broke, there must be an Exception?

**Comment by nsiatras** [comment]
I suggest to take a look and find the Disconnect interval.

Notice that TCPClient "understands" that the connection dropped while you SendData
and that SendData method always raises and exception

**Comment by nsiatras** [comment]
PS. I also noticed that your 
```public void sendData(byte b[]) ``` is not sychronized
and that calls ```tickOneTime(TICK_TIMEOUT, 10000, true);```

**Comment by fohnbit** [comment]
Thank you ... I guess I found the problem. There is an execption in "parseResponse method" but the Exception show me "null". I check this first. Thanks for help

**Comment by fohnbit** [comment]
btw: When I send data to the TCP Client. Did you expect any response?
It seems the problem is: 
```
		try {
					super.getConnectors().get(0).fConnection.setSoTimeout(15000);
				} catch (SocketException e) {
					e.printStackTrace();
				}
```

Sometimes the Huawei Inverter need a long time (sometimes over 10s) to response.
When I send a request, the disconnect always happen after this time (15s):
12:22:00.090 fox: [pool-11-thread-1] DEBUG c.g.communication.huawei.Huawei - send: 0x000900000006100395550061
12:22:15.092 fox: [Thread-124] DEBUG c.g.communication.huawei.Huawei - Disconnected after 180514

**Comment by nsiatras** [comment]
It was my first assumption that you might have set a timeout somewhere.
Initially o thought that this timeout interval was at the inverter side.

Remove the setSoTimeout and you will be good to go

**Comment by fohnbit** [comment]
Hi!

Thank you.. yes this solve the problem. But I need a timeout.
So I set this higher and remove my own timeout counter.

Great support!

**Comment by fohnbit** [comment]
done

**Comment by nsiatras** [comment]
> Great support!

You are most welcome!

**Comment by fohnbit** [comment]
Just a question beside:
I tried to add the Exception information in the OnDisconnect:
```
/**
	 * A connector of this client has been disconnected.
	 *
	 * @param connector
	 */
	public abstract void OnDisconnect(TCPConnector connector, Exception ex);
```

Updated the other code lines, but get an abstract error, when I start the code. Eclipse show me no error.
Maybe you can add this or give me a hint how to add?

Then I know, when the OnDisconnect is fired, if there was an exception or a regular Stop.

Thank you!

**Comment by nsiatras** [comment]
Hello,

Only possible way for a host to understand that a client went off in a not graceful way
is to send data to the client. Send data will throw an exception
